version: '3'

services:
  recommender-api:
    build: ./recommender-api
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
    ports:
      - "4566:4566"
      - "4571:4571"
